# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/bullseye64"

  config.vm.network "private_network", ip: "192.168.56.200"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = "8192"
    libvirt.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
      # Installation prérequis
	  apt update
	  apt install -y nginx curl git ca-certificates gnupg lsb-release build-essential
      
	  # Installation docker
	  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
	  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt update
	  apt install -y docker-ce docker-ce-cli containerd.io    
	  usermod -aG docker vagrant
	  
	  # Installation minikube
	  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      install minikube-linux-amd64 /usr/local/bin/minikube
	  rm minikube-linux-amd64
	  
	  # Copie de fichiers
	  cp /vagrant/start.sh /home/vagrant/start.sh
	  chmod +x /home/vagrant/start.sh
	  chown vagrant start.sh
	  
	  cp /vagrant/nginx.conf /etc/nginx/nginx.conf
	  systemctl reload nginx
	  
	  cp /vagrant/motd /etc/motd
	  
	  cp /vagrant/kubectl /usr/bin/kubectl
	  chmod +x /usr/bin/kubectl
	
  SHELL
  
end
